### ISSUE TITLE
[challenge]: add some of these buttons to the top right side panel

### ISSUE THREAD

**Issue by PickleNik** [bautistaaa/typehero#143]
<img width="170" alt="Screenshot 2023-08-27 at 1 33 05 PM" src="https://github.com/bautistaaa/typehero/assets/31113245/0318d915-272e-4851-8551-1019a80852b2">

 - [x] #458 (visual only)
 -  - [x] #478 
 - [x] #457
 - [x] settings (already exists)
 - [x] #460
 - - [x] #480

**Comment by MahendraBishnoi29** [comment]
@bautistaaa @PickleNik I'm new here would love to start with some good first issues 👍🏻😊

**Comment by PickleNik** [comment]
oh no the images are gone from the issue aren't they

**Comment by PickleNik** [comment]
lemme try to find em

**Comment by PickleNik** [comment]
it's these buttons @MahendraBishnoi29 
![image](https://github.com/bautistaaa/typehero/assets/31113245/04749b50-f98b-4453-b563-a553e2a15c52)

feel free to split it into sub-issues for each button and just take one :)

**Comment by PickleNik** [comment]
I don't think we need all of them, 
 - ignore the bookmark
 - ignore the 2nd one
the rest of them are
 - reset
 - editor shortcuts (it's basically VSC so we can copy the same popup
![image](https://github.com/bautistaaa/typehero/assets/31113245/7ba5f7b9-3b4a-4eda-b695-2a7630d036c6)
 - settings (already exists)
 - fullscreen

**Comment by PickleNik** [comment]
now that I think of it this is prolly not a good-first-issue

**Comment by PickleNik** [comment]
> now that I think of it this is prolly not a good-first-issue

but #457 is

**Comment by PickleNik** [comment]
> @bautistaaa @PickleNik I'm new here would love to start with some good first issues 👍🏻😊

I split this one into a bunch of sub-issues, feel free to assign yourself to whichever you like :)

**Comment by MahendraBishnoi29** [comment]
@PickleNik got it lemme see, thanks for your help 🙌

**Comment by PickleNik** [comment]
>  I'm not able to assign it to myself so you can do it😁

which ones? just ping me in em

**Comment by PickleNik** [comment]
> Someone is already working on almost all of them, so you can assign any one according to your convenience 🙂

Do u wanna take #480 ? Otherwise u could take #457 after @pizzaintheoven pushes what he has if it's not complete

**Comment by PickleNik** [comment]
or just some other issue unrelated

**Comment by MahendraBishnoi29** [comment]
sure, assign me any one of those.

**Comment by MahendraBishnoi29** [comment]
> @MahendraBishnoi29 Feel free pick up #457 i merge all the code. you can see the code here. #497. Feel free to change the code :D. I will be out of town for a week, join the discord if you have question.

that would be nice! please do share the invite link :)

**Comment by PickleNik** [comment]
> that would be nice! please do share the invite link :)

  <a href="https://discord.gg/trashdev" target="_parent">
    <img alt="Discord" height=20 src="https://img.shields.io/discord/796594544980000808?style=&logo=discord&logoColor=white&label=%20&labelColor=%237389D8&color=%237389D8" />
  </a>
