### ISSUE TITLE
you should be able to click labels in reports

### ISSUE THREAD

**Issue by Hacksore** [bautistaaa/typehero#268]
labels should be clickable in all report modals

![Image](https://user-images.githubusercontent.com/996134/254570360-ff31f156-bc13-4052-a0c9-4fa4d6ddd29e.png)

**Comment by andresmarpz** [comment]
Is this supposed to be closed or maybe hasn't been fixed yet?

**Comment by Hacksore** [comment]
This indeed is fixed
