### ISSUE TITLE
Need designs for profile page 

### ISSUE THREAD

**Issue by bautistaaa** [bautistaaa/typehero#382]
see #10

**Comment by jhechtf** [comment]
@ernestoresende you think this is something you could do on the figma file or should I take a stab at it?
cc: @PickleNik

**Comment by emalineg** [comment]
using max and nik's design to continue developing profile

**Comment by emalineg** [comment]
passing this to max!

**Comment by maxdemaio** [comment]
Desktop was done in #504! Now, we just need to work on mobile. Had some ideas I listed in the PR description of #504 and added some ideas to the Figma. If anyone wants to tackle that or pair lmk!

**Comment by PickleNik** [comment]
> If anyone wants to tackle that or pair lmk!

![image](https://github.com/bautistaaa/typehero/assets/31113245/e42cf314-f2f4-44b1-a14b-0c481ceafad0)

**Comment by maxdemaio** [comment]
Created a branch for this work here! https://github.com/bautistaaa/typehero/tree/profile-2
