### ISSUE TITLE
Two small typos in email

### ISSUE THREAD

**Issue by cloudnothings** [bautistaaa/typehero#387]
File: /apps/email/emails/waitlist-user-signup.tsx 
line 38 :s/apperciate/appreciate
line 41 :s/extremelly/extremely
I don't know how to make a pr or anything so figured I post as an issue

**Comment by JJooaa** [comment]
Hey typehero people! I can take this.

**Comment by bautistaaa** [comment]
this copy isnt finalized yet(just placeholder). so we can ignore the copy for now
