### ISSUE TITLE
Explore Cards design change

### ISSUE THREAD

**Issue by PickleNik** [bautistaaa/typehero#395]
<img width="1330" alt="Screenshot 2023-08-22 at 10 01 16 PM" src="https://github.com/bautistaaa/typehero/assets/31113245/8a789ad6-4231-419d-8798-5a88420c7fb2">
<img width="634" alt="Screenshot 2023-08-22 at 10 01 47 PM" src="https://github.com/bautistaaa/typehero/assets/31113245/1d6917c8-813f-426f-88f4-9233ecaf0e80">

**Comment by bautistaaa** [comment]
i like these new cards way better!

we can keep the colors isolated to the difficulty badge and outline on hover?

**Comment by thomaskant** [comment]
I am going to agree with @bautistaaa these look better! Keep up the great work! 🚀
