### ISSUE TITLE
[bug] clicking on any author on the amogus feature card redirects to notfound

### ISSUE THREAD

**Issue by is-it-ayush** [bautistaaa/typehero#413]
### Bug
When you click on the amogus feature card as seen in the video below. You'll be redirected to not found page. This shouldn't occur as the Card is just for show. 

### Solution
Add `pointer-events-none` to the author.

### SC
[Screencast from 2023-08-24 21-27-44.webm](https://github.com/bautistaaa/typehero/assets/36449128/19cc69ad-03cc-4fac-a7b5-f045586cb527)

**Comment by iamsadat** [comment]
@is-it-ayush 
Is the issue fixed? 
The Card's username is not redirection to 404 anymore.

**Comment by bautistaaa** [comment]
this is fixed i’ll close
