### ISSUE TITLE
[Comments]: Ability to Upvote a comment

### ISSUE THREAD

**Issue by basokant** [bautistaaa/typehero#431]
### Description

On the comment component (in the challenge and solution tabs within a challenge page), a user should be able to upvote a comment. The number of upvotes should display within a comment.

### Explanation

We should follow a similar style to Leetcode comment upvoting UI, except we will only allow upvoting:

<img width="677" alt="image" src="https://github.com/bautistaaa/typehero/assets/70033855/eee3d23a-4edf-4bdf-9f21-433c536782f2">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bautistaaa** [comment]
should be able to reuse the thumb from the challenge upvote(break it out). look up useOptimistic cause it’s jank af right now
