### ISSUE TITLE
Light mode Waitlist Banner looks goofy, pls fix

### ISSUE THREAD

**Issue by PickleNik** [bautistaaa/typehero#441]
![image](https://github.com/bautistaaa/typehero/assets/31113245/b8826f61-415e-4e2a-ab14-153dbfd8d1f0)

**Comment by Mahmoudgalalz** [comment]
Taking it

**Comment by maxdemaio** [comment]
Addressed this in https://github.com/bautistaaa/typehero/pull/443 👍🏻
