### ISSUE TITLE
[CI] disable import/order eslint rule

### ISSUE THREAD

**Issue by is-it-ayush** [bautistaaa/typehero#448]
### current behaviour
CI flags `import/order` as warning.

### expected behaviour
CI shouldn't warn about  `import/order` rule. (running `pnpm checks`) 

### Solution
disable it.

**Comment by is-it-ayush** [comment]
update: also disable `react/function-component-definition`. it's kinda stupid too.

**Comment by jhechtf** [comment]
#449 Merged, closing issue.
