### ISSUE TITLE
[Bug]: Comment pagination is broken

### ISSUE THREAD

**Issue by basokant** [bautistaaa/typehero#453]
### What happened?

The pagination for comments is not working correctly. 

* Comments are a part of multiple pages for some reason. 

<img width="1440" alt="image" src="https://github.com/bautistaaa/typehero/assets/70033855/1daece54-1b1e-4495-aea3-7de09fc5ea39">

* The total comments number is incorrect (this is my bad lolll). It only seems to account for one page of replies. From the seed data, total parent comments = 50, each comment has 2 replies, therefore total replies = 100, and total comments = 150 != 70

<img width="1440" alt="image" src="https://github.com/bautistaaa/typehero/assets/70033855/a01fd0f1-fa06-4bcc-88f8-baaebe797add">

See demo:

Demo: https://drive.google.com/file/d/1Ir0-rQ_jtDMYwo6WQNQXVLl1e6IJuFbS/view?usp=sharing

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by maxdemaio** [comment]
prisma.comment.count could be an idea or we could just see if we have the information already
