### ISSUE TITLE
editor shortcuts (it's basically VSC so we can copy the same popup

### ISSUE THREAD

**Issue by PickleNik** [bautistaaa/typehero#457]
<img width="82" alt="Screenshot 2023-08-27 at 1 31 18 PM" src="https://github.com/bautistaaa/typehero/assets/31113245/7973fefc-d6df-4757-887e-211c617bc5f3">

![image](https://github.com/bautistaaa/typehero/assets/31113245/7ba5f7b9-3b4a-4eda-b695-2a7630d036c6)

**Comment by Hacksore** [comment]
@pizzaintheoven was working on this but not sure how far he got

**Comment by pizzaintheoven** [comment]
Let me push what I have once I get back into the town.

**Comment by pizzaintheoven** [comment]
pushed all the code, anyone can pick this ticket up to complete the work

**Comment by PickleNik** [comment]
assigning @MahendraBishnoi29 to this

**Comment by PickleNik** [comment]
for some reason they don't show up in the list for assignees but just imagine as if they're assigned to this
<img width="334" alt="Screenshot 2023-08-29 at 9 15 30 AM" src="https://github.com/bautistaaa/typehero/assets/31113245/dceab4b8-e522-42a3-8e5d-c1311032f1bc">

**Comment by PickleNik** [comment]
is this done? can i close it?

**Comment by PickleNik** [comment]
it seems done on local server, if anybody wants to make it better just open a PR don't ask 👏🚀
