### ISSUE TITLE
reset editor button (visual only)

### ISSUE THREAD

**Issue by PickleNik** [bautistaaa/typehero#458]
<img width="170" alt="Screenshot 2023-08-27 at 1 32 37 PM" src="https://github.com/bautistaaa/typehero/assets/31113245/073e6f18-81fd-431d-88d2-a94a8a93a60f">

**Comment by Tylopilus** [comment]
Might wait for this until https://github.com/bautistaaa/typehero/pull/463 is merged

**Comment by PickleNik** [comment]
Mergd 👍

**Comment by Tylopilus** [comment]
lets close this one
