### ISSUE TITLE
fullscreen editor

### ISSUE THREAD

**Issue by PickleNik** [bautistaaa/typehero#460]
<img width="90" alt="Screenshot 2023-08-27 at 1 33 17 PM" src="https://github.com/bautistaaa/typehero/assets/31113245/adf1c8e9-c7e3-430f-bd6f-dd6ecc4cf3e6">

**Comment by Tylopilus** [comment]
let me see if I can manage this one. What is the intent of the fullscreen? Hiding the left column?

**Comment by Hacksore** [comment]
We are not sure yet but what's in #463 is good enough for now until we think about the UX.

**Comment by Tylopilus** [comment]
I have updated the PR with the fix. I noticed though that running `pnpm format` in `/` did not catch the issue like CI did. I had to navigate into packages/monaco and run `pnpm format` to get the message.
