### ISSUE TITLE
[Bug]: challenge card clips behind when hovered on /tracks

### ISSUE THREAD

**Issue by is-it-ayush** [bautistaaa/typehero#485]
This is possibly a width issue with `max-md:scale-110` on challenges over at /tracks. I have css skill issue. The challenge card shouldn't clip behind.

### SC

[Screencast from 2023-08-28 23-20-11.webm](https://github.com/bautistaaa/typehero/assets/36449128/3a1df25e-2a56-4d03-b577-c5c5152b5336)

**Comment by maxdemaio** [comment]
I can pick this up!

**Comment by maxdemaio** [comment]
https://github.com/bautistaaa/typehero/blob/ayu/tracks_update/apps/web/src/app/tracks/_components/track-card.tsx#L42

If you remove overflow-hidden on this line you should be good! Going to close this now since it will be included in @is-it-ayush's PR 🚀

**Comment by maxdemaio** [comment]
https://github.com/bautistaaa/typehero/assets/44373521/bb223859-3973-406f-9846-88c9cf256266
