### ISSUE TITLE
[Issue Template]: include an all option on browsers.

### ISSUE THREAD

**Issue by is-it-ayush** [bautistaaa/typehero#486]
We should have a `All` option representing all browsers. Edit the template & add one.

![image](https://github.com/bautistaaa/typehero/assets/36449128/335457d3-9a91-4ee1-aad7-b100abd638ff)

**Comment by jproberson** [comment]
completed with:
https://github.com/bautistaaa/typehero/pull/488

**Comment by is-it-ayush** [comment]
Thank you for the contribution @jproberson. I'm closing this as completed. 💙
