### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by TheBharatMishra** [bautistaaa/typehero#520]
### What happened?

the web page doesnt respond well with darkmode extension. color scheme messes up words cant be seen properly. 

https://github.com/bautistaaa/typehero/assets/67362217/c585fff9-8f5a-493b-8261-37981cdb9402

**Comment by dylf** [comment]
Can anything even be done about a third party extension not working well? The site itself supports dark mode, this seems like a non-issue to me :man_shrugging:

**Comment by bautistaaa** [comment]
we can’t control 3rd party extensions. please use the one inside the app
