### ISSUE TITLE
[Feature]: border on code pill

### ISSUE THREAD

**Issue by Hacksore** [bautistaaa/typehero#527]
### Description
Make the code pills have the nice boarder like leetcode.com

![image](https://github.com/bautistaaa/typehero/assets/996134/7d88cfcc-4972-4d73-a945-bcc57948edd8)

> [!IMPORTANT]
> ## this is needed fr fr ong

**Comment by maxdemaio** [comment]
> [!IMPORTANT]
> ## ayo
>
> 🥳

**Comment by maxdemaio** [comment]
> [!WARNING]
> ## ayo
>
> 🥳

**Comment by maxdemaio** [comment]
> [!NOTE]
> ## ayo
>
> 🥳

**Comment by Milind-Jamnekar** [comment]
Is this isssue resolved or not ? i can do this in 30 min i guess

**Comment by Hacksore** [comment]
@Milind-Jamnekar right now @MVAodhan is cooking on this via #531.

**Comment by MVAodhan** [comment]
Theres a merge conflict between the two bigmen of this repo

**Comment by Hacksore** [comment]
@MVAodhan accept my suggestion and we can deploy it to staging and see what @bautistaaa thinks.
