### ISSUE TITLE
[Bug]: waitlist form throws error in dev

### ISSUE THREAD

**Issue by bautistaaa** [bautistaaa/typehero#548]
### What happened?

navigate to `/waitlist`

<img width="500" alt="CleanShot 2023-09-01 at 00 32 05@2x" src="https://github.com/bautistaaa/typehero/assets/3660667/95501a1f-eefa-4c85-af03-644e2407c5c0">

### What browsers are you seeing the problem on?

All

**Comment by cosmiclasagnadev** [comment]
Think I have an idea about this. Would love to work on it @bautistaaa

**Comment by Hacksore** [comment]
Fixed via #550
